{
   "jsonClass":"Bundle",
   "type":"ComboChart",
   "data":{
      "series":{
         "sort":"series-asc"
      },
      "keys":{
         "sort":"key-asc"
      },
      "fields":{
         "cToggleTypeCol":[
            {
               "name":"ds_3b_OTcompare.Week"
            }
         ],
         "keys":[
            {
               "name":"ds_3b_OTcompare.OTDate"
            },
            {
               "name":"ds_3b_OTcompare.EmpName"
            }
         ],
         "operable":{
            "values":[
               {
                  "id":"columnEscortAvgLine",
                  "name":"ds_3b_OTcompare.OT_HOURS",
                  "op":"sum"
               }
            ]
         }
      }
   },
   "width":"500",
   "height":"510",
   "dataGroupKey":"timePeriodOptions",
   "title":"OT Comparison",
   "subtitle":"",
   "yAxisArray":"OT Hours",
   "colorSeriesArray":"#7cb5ec,#434348,#90ed7d,#f7a35c,#ffc0cb,#f15c80,#e4d354,#8085e8,#8d4653,#91e8e1,#d89b00,#9fb27e,#c6c6cd,#284040,#5ead06",
   "interpolateXAxisKey":"default",
   "seriesInsertKey":"default",
   "formatSeriesInsertCast":"",
   "xTicksKey":"string",
   "formatXTicksCast":"",
   "orderingKey":"monthString",
   "formatOrderingCast":"",
   "interpolateGroupbyKey":"default",
   "fixedGroupbyClassCast":"fixedGroupbyClass={'groupby1':['asd']}",
   "formatLegendCast":"formatLegend={'columnInducedGroupby.L1': function(dataZero) {   return dataZero.columnNameWithoutOp;   } };",
   "legendKey":"allGroupby",
   "cToggleKey":"default",
   "toolTipKey":"default",
   "legendEscortLines":"Average",
   "typeAntiType":"",
   "formatToolTipCast":"formatToolTip={'columnInducedGroupby.L1':{valueDecimals:2,valuePrefix:'$',valueSuffix:' USD'}}",
   "inducedKey":"default",
   "formatInducedCast":"",
   "valueOperationKey":"default",
   "formatValueOperationCast":"operation.prototype.value=function(){ return [this.A-this.B];}",
   "formatValueOperationArg":"A",
   "xTicksRotation":"0"
}